version: '3.8'

services:
  hello-world:
    build: .
    ports:
      - "5001:5000" # Map port 5000 in the container to port 5001 on the host
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    container_name: hello-world-app
